In [16]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [18]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [19]:
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon", "Tue", "Wed", "Thur", "Fri"], columns=["Almond butter", "Peanut butter", "Cashew butter"])

In [20]:
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [22]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index=["Price"], columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [25]:
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [26]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [28]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tue  Wed  Thur  Fri
Price  240  138  458   232  142

In [30]:
weekly_sales["Total ($)"]= daily_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon              12             15              0        240
Tue               3              3              7        138
Wed               9             19             18        458
Thur              4              6             12        232
Fri               1              6              7        142